email: #credential E-mail
password: #Credential Password

disableAntiLock: False

remote: False

experienceLevel:
 internship: False
 entry: False
 associate: False
 mid-senior level: False
 director: False
 executive: False
 
jobTypes:
 full-time: True
 contract: False
 part-time: False
 temporary: False
 internship: False
 other: False
 volunteer: False
 
date:
 all time: True
 month: False
 week: False
 24 hours: False
 
positions:
 - graphiste
 - Web designers
 - Web digital
 - Web marketing
 - Design digital
 - Design digital
 - Design graphique
 - UI UX

locations:
 - Ile-de-france
 #- A second location
 #- A third location
 #- ...
distance: 25

outputFileDirectory: C:\Laragon\www\LinkedIn-Easy-Apply-Bot\output

companyBlacklist:
 #- Agence Iceberg
 #- company2

titleBlacklist:
 - Alternance
 - alternant
 - Stage
 - stagiaire
 #- word2

uploads:
 resume: C:\Laragon\www\LinkedIn-Easy-Apply-Bot\resume\CV-Infographie-_-webdesigner.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  # - Associate's Degree
  # - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: univeristyGpa ---------------
universityGpa: 4.0

# ------------ Additional parameters: languages ---------------
languages:
 english: Professional # None, Conversational, Professional, Native or bilingual


# ------------ Additional parameters: years of INDUSTRY experience ---------------
# How many years of TECHNOLOGY experience do you currently have? (whole numbers only)
industry:
 # normal ones
 Accounting/Auditing: 4
 Administrative : 4
 Advertising : 4
 Analyst : 4
 Art/Creative: 4
 Business Development: 4
 Consulting: 4
 Customer Service: 4
 Distribution Design: 4
 Education: 4
 Engineering: 4
 Finance: 4
 General Business: 4
 Health Care Provider: 4
 Human Resources: 4
 Information Technology: 4
 Legal: 4
 Management: 4
 Manufacturing: 4
 Marketing: 4
 Public Relations: 4
 Purchasing: 4
 Product Management: 4
 Project Management: 4
 Production: 4
 Quality Assurance: 4
 Research: 4
 Sales: 4
 Science: 4
 Strategy/Planning: 4
 Supply Chain: 4
 Training: 4
 Writing/Editing: 4
 # end normal ones
 # put your custom ones here
 #C++: 4
 #Python: 1
 # default to put for any skill that you did not list
 default: 4
 # end custom ones


# ------------ Additional parameters: years of technology experience ---------------
# How many years of work experience do you have using TECHNOLOGY? (whole numbers only)
technology:
 #python: 4
 #selenium: 4
 Illustrator: 4
 Indesign: 4
 Figma: 4
 Adobe XD: 4
 Photoshop: 4
 Wordpress: 4
 Wix: 4
 Prestashop: 4
 # default to put for any skill that you did not list
 default: 4
# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Eden
 Last Name: Benaim
# Phone Country Code: Canada (+1) # See linkedin for your country code, must be exact
# Mobile Phone Number: 1234567894
# Street address: 123 Fake Street
# City: Red Deer, Alberta # Include the state/province as well!
# State: YourState
# Zip: YourZip/Postal
# Linkedin: https://www.linkedin.com/in/my-linkedin-profile
# Website: https://www.my-website.com # github/website is interchangable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: None
# race: None
# vetran: None
# disability: None
# citizenship: Canadian
